"""
Django settings for basictest project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from foundations.ecosystem_foundations.utils.read_env import EnvironVarLoader

# Build paths inside the project like this: BASE_DIR / 'subdir'.
envloader = EnvironVarLoader()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TEST_FLAG = envloader.get("TEST_FLAG", "1").lower() in ("1", "true", "yes")

if TEST_FLAG:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    #SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')
else:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True

    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True



REDIS_URL = envloader.get("REDIS_URL", "redis://redis:6379/1")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h_+om6uw0xq_j*$$3_jj9^dwhem77v!p)necl3wjyps^o(!f5z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False



AUTH_USER_MODEL = "users.User"

CORS_ALLOW_CREDENTIALS = True

if TEST_FLAG:

    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost",
        "django"
    ]

    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
    ]

    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173"
    ]
else:

    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost"
    ]

    CORS_ALLOWED_ORIGINS = [
        "https://127.0.0.1",
        "https://localhost"
    ]

    CSRF_TRUSTED_ORIGINS = [
        "https://nginx.kyc.internal",
        "https://127.0.0.1"
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'pghistory',
    'pgtrigger',
    'foundations.ecosystem_foundations.base',
    'foundations.ecosystem_foundations.automation',
    'foundations.ecosystem_foundations.globalparams',
    'foundations.ecosystem_foundations.iam',
    'foundations.ecosystem_foundations.labels',
    'foundations.ecosystem_foundations.storedquery',
    'foundations.ecosystem_foundations.users',
    'foundations.ecosystem_foundations.watchdog',
    'ecosystem_alerts.alerts',
    'ecosystem_schedule.schedule',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'basictest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'basictest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3'
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': envloader.get('DATABASE_NAME', defaultVal='KYCcontroller'),
        'USER': envloader.get('DATABASE_USER', defaultVal='KYCuser'),
        'PASSWORD': envloader.get('DATABASE_PASSWORD', defaultVal='KYCus3r'),
        'HOST': envloader.get('DB_HOST', defaultVal='db'),
        'PORT': envloader.get('DB_PORT', defaultVal='5432')
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = "/app/media"
MEDIA_URL = "/media/"